- name: backup folder exists ont the host
  ansible.builtin.file:
    path: "{{ nc_archive_path }}"
    state: directory

- name: copy config in archive
  ansible.builtin.shell: "rsync -r --exclude='*.sample.*' {{nextcloud_webroot}}/config/ {{ nc_archive_path }}/config/"

- name: download server files for current version
  vars:
    nc_server_dl_url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nc_status.versionstring }}.zip"
  ansible.builtin.get_url:
    url: "{{ nc_server_dl_url }}"
    checksum: "sha512:{{ nc_server_dl_url }}.sha512"
    dest: "{{ nc_archive_path }}/nextcloud-{{ nc_status.versionstring }}.zip"

- name: get the list of apps installed
  command: "php {{nextcloud_webroot}}/occ app:list --output=json"
  become_user: "{{ nextcloud_websrv_user }}"
  become: true
  become_method: su
  become_flags: -s /bin/sh
  register: _nc_app_list

- name: export the list of apps in the backup
  copy:
    content: "{{ _nc_app_list.stdout | from_json | to_nice_json }}"
    dest: "{{ nc_archive_path }}/installed_apps.json"
