---
- name: "[INSTALL] - Debian 11 only - repository for php 8.0"
  ansible.builtin.apt_repository:
    repo: deb https://packages.sury.org/php/ bullseye
    state: present
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "11")

- name: "[INSTALL] - Required and recommended packages are installed."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - imagemagick
    - smbclient
    - "php{{ php_ver }}-fpm"
    - "php{{ php_ver }}-gd"
    - "php{{ php_ver }}-ldap"
    - "php{{ php_ver }}-imap"
    - "php{{ php_ver }}-curl"
    - "php{{ php_ver }}-intl"
    - "php{{ php_ver }}-bz2"
  notify:
    - Start php-fpm

- name: "[INSTALL] - php-json is installed (PHP < 8)"
  ansible.builtin.package:
    name: "php{{ php_ver }}-json"
    state: present
  when: php_ver is version("8", "<")

- name: "[INSTALL] -  PHP extra Packages are installed."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_pkg_spe }}"

- name: "[INSTALL - PHP Database client - MySQL."
  ansible.builtin.package:
    name: "php{{ php_ver }}-mysql"
    state: present
  when: (nextcloud_db_backend == "mysql") or (nextcloud_db_backend == "mariadb")

- name: "[INSTALL - PHP Database client - PostgreSQL."
  ansible.builtin.package:
    name: "php{{ php_ver }}-pgsql"
    state: present
  when: (nextcloud_db_backend == "pgsql")

- name: "[INSTALL] -  APCu is installed."
  ansible.builtin.package:
    name: "{{ php_pkg_apcu }}"
    state: present
