---
- name: "[DEBIAN REPO] Debian - repository for php"
  when: (ansible_facts['distribution'] == "Debian")
  block:
    - name: Debian php repository - install required packages
      ansible.builtin.package:
        name: gpg
        state: present
    - name: Debian php repository - GPG key
      ansible.builtin.apt_key:
        url: "{{ php_repo_debian_gpg }}"
        state: present
    - name: Debian php repository - APT source
      ansible.builtin.apt_repository:
        repo: "{{ php_repo_debian_apt_source }}"
        state: present

- name: "[INSTALL] - Required and recommended packages are installed."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - imagemagick
    - smbclient
    - "php{{ php_ver }}-fpm"
    - "php{{ php_ver }}-gd"
    - "php{{ php_ver }}-ldap"
    - "php{{ php_ver }}-imap"
    - "php{{ php_ver }}-curl"
    - "php{{ php_ver }}-intl"
    - "php{{ php_ver }}-bz2"
  notify:
    - Start php-fpm

- name: "[INSTALL] - php-json is installed (PHP < 8)"
  ansible.builtin.package:
    name: "php{{ php_ver }}-json"
    state: present
  when: php_ver is version("8", "<")

- name: "[INSTALL] -  PHP extra Packages are installed."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_pkg_spe }}"

- name: "[INSTALL] - PHP Database client - MySQL."
  ansible.builtin.package:
    name: "php{{ php_ver }}-mysql"
    state: present
  when: (nextcloud_db_backend == "mysql") or (nextcloud_db_backend == "mariadb")

- name: "[INSTALL] - PHP Database client - PostgreSQL."
  ansible.builtin.package:
    name: "php{{ php_ver }}-pgsql"
    state: present
  when: (nextcloud_db_backend == "pgsql")

- name: "[INSTALL] -  APCu is installed."
  ansible.builtin.package:
    name: "{{ php_pkg_apcu }}"
    state: present
