---
# facts specific for each distributions and versions
# defaults keys are global for each family/distribution
debian:
  defaults:
    mysql_daemon: mariadb
    # thoses 2 are globals for debian family:
    nextcloud_websrv_user: "www-data"
    nextcloud_websrv_group: "www-data"
    upgrade_packages_first: false

ubuntu:
  defaults:
    mysql_daemon: mysql
