---
# define parameters depending for the php version installed
# for any new version, only specify keys with values different from defaults
# should work for php >= 7.4
defaults:
  php_dir: "/etc/php/{{ php_ver }}"
  php_bin: "php-fpm{{ php_ver }}"
  php_pkg_apcu: "php{{ php_ver }}-apcu"
  php_pkg_spe:
    - "php{{ php_ver }}-bcmath"
    - "php{{ php_ver }}-gmp"
    - "php{{ php_ver }}-imagick"
    - "php{{ php_ver }}-mbstring"
    - "php{{ php_ver }}-redis"
    - "php{{ php_ver }}-xml"
    - "php{{ php_ver }}-zip"
  php_socket: "/run/php/php{{ php_ver }}-fpm.sock"
